export interface Env {
	VITE_CONTEMBER_ADMIN_API_BASE_URL: string
	VITE_CONTEMBER_ADMIN_INVITE_TOKEN: string
	VITE_CONTEMBER_ADMIN_LOGIN_TOKEN: string
	VITE_CONTEMBER_ADMIN_PROJECT_NAME: string
	VITE_CONTEMBER_PUBLIC_TOKEN: string
	role: string
}
