export interface Env {
	VITE_CONTEMBER_ADMIN_API_BASE_URL: string
	VITE_CONTEMBER_CHECKEMAIL_TOKEN?: string
	VITE_CONTEMBER_SIGNUP_TOKEN: string
	VITE_CONTEMBER_ADMIN_LOGIN_TOKEN: string
	BASE_URL: string
	APP_URL?: string
	VITE_CONTEMBER_ADMIN_PROJECT_NAME: string
	role: string
}
