name: Deploy

on:
  push:
    branches:
      - 'deploy/prod'
      - 'deploy/staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create .env.production from secret
        run: |
          if [[ "${GITHUB_REF##*/}" == "deploy/prod" ]]; then
            echo "${{ secrets.ENV_FILE_PROD }}" > .env.production
          else
            echo "${{ secrets.ENV_FILE_TEST }}" > .env.production
          fi

      - name: Deploy Contember
        run: |
          if [[ "${GITHUB_REF##*/}" == "deploy/prod" ]]; then
            yarn run deploy ${{ secrets.CONTEMBER_DEPLOY_DSN_PROD }} --yes
          else
            yarn run deploy ${{ secrets.CONTEMBER_DEPLOY_DSN_TEST }} --yes
          fi

#     Uncomment this block if you are using Cloudflare Workers for Contember actions

#      - name: Setup Contember actions variables
#        run: bash .github/scripts/setup-actions-variables.sh
#        env:
#          CONTEMBER_DEPLOY_DSN: ${{ secrets.CONTEMBER_DEPLOY_DSN }}
#          CONTEMBER_ACTIONS_VARIABLES: ${{ secrets.CONTEMBER_ACTIONS_VARIABLES }} # [{ name: "apiKey", value: "new-api-key-value" }, { name: "baseUrl", value: "http://localhost/foo-bar" }]
#
#      - name: Deploy action worker
#        uses: cloudflare/wrangler-action@v3.4.0
#        with:
#          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#          workingDirectory: "worker"
#          secrets: |
#            CONTEMBER_API_TOKEN
#            CONTEMBER_ACTIONS_SECRET_KEY
#        env:
#          CONTEMBER_API_TOKEN: ${{ secrets.CONTEMBER_API_TOKEN }}
#          CONTEMBER_ACTIONS_SECRET_KEY: ${{ secrets.CONTEMBER_ACTIONS_SECRET_KEY }}
